### ISSUE TITLE
Websocket for w5500

### ISSUE THREAD

**Issue by MaxESP** [arduino-libraries/Ethernet#114]
Can you provide a websocket server example for w5500

That would be Cool

Thanks a lot

**Comment by sandeepmistry** [comment]
I think this is better answered on the forum: https://forum.arduino.cc

However, it should be straightforward to port this example to use Ethernet: https://github.com/arduino-libraries/ArduinoHttpClient/blob/master/examples/SimpleWebSocket/SimpleWebSocket.ino
