### ISSUE TITLE
Chinese clones and issues W5100 

### ISSUE THREAD

**Issue by Rotzbua** [arduino-libraries/Ethernet#117]
Here a clear warning: There are some bugged clone ethernet shields on the market!
In particular the cheep chinese 5$ W5100 boards have a bug which cause issues.

## Observation

* Ethernet not recognized by some routers
* connection drops
* long delays
* hot components

## Detection

A simple test to detect problems with soft- or hardware: ICMP (ping) to device.
* Background: ICMP packages are replied by hardware automatically after the W5100 is initialized successfully.
* Test: ping to device
* Ping time = with spikes/ not constant ==> hardware problem
* Ping time = constant ==> maybe no hardware problem

## Solution

* fix by soldering new components or bridges
* buy original or from serious manufacturer e.g. seedstudio, dfrobot,...

## Reference

Several boards with bug description and solution:

https://arduinodiy.wordpress.com/2017/04/12/the-w5100-bug/

Discussion on the arduino forum:

https://forum.arduino.cc/index.php?topic=351477.30

**Comment by per1234** [comment]
Thanks for sharing this valuable information @Rotzbua. Since there is no action to take within this code base, I'll go ahead and close it, but it will continue to serve as a reference.
