### ISSUE TITLE
Ethernet library compile warning 

### ISSUE THREAD

**Issue by RichardSelmanXX** [arduino-libraries/Ethernet#122]
Reposted from main IDE.  IDE 1.8.10.  Controllino MEGA, simple ethernet test sketch......

Get this on compile....

In file included from C:\Program Files (x86)\Arduino\libraries\Ethernet\src\Dns.cpp:8:0:

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\Dns.cpp: In member function 'uint16_t DNSClient::BuildRequest(const char*)':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\utility/w5100.h:457:25: warning: result of '(256 << 8)' requires 18 bits to represent, but 'int' only has 16 bits [-Wshift-overflow=]

 #define htons(x) ( (((x)<<8)&0xFF00) | (((x)>>8)&0xFF) )

                      ~~~^~~

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\Dns.cpp:164:18: note: in expansion of macro 'htons'

  twoByteBuffer = htons(QUERY_FLAG | OPCODE_STANDARD_QUERY | RECURSION_DESIRED_FLAG);

                  ^~~~~

**Comment by per1234** [comment]
From the original issue https://github.com/arduino/Arduino/issues/9539: 
*matthijskooijman commented 32 minutes ago*
>Seems like a warning, which is also harmless (code works as expected AFAICS).
>
>Still would be good to fix, though.

**Comment by thekunalsaini** [comment]
@RichardSelmanXX  Is there any documentation you have follow for this

**Comment by 5kuby** [comment]
is it still unfixed?

**Comment by ckohrt** [comment]
Any news here?

**Comment by mgnthe54** [comment]
Hello, for some time I have also been getting this alert message on one of my PCs ....
Anyone have any idea where the warning came from?
Thank you

**Comment by ckohrt** [comment]
> Hello, for some time I have also been getting this alert message on one of my PCs ....
> Anyone have any idea where the warning came from?
> Thank you

I just ignore it.

**Comment by mgnthe54** [comment]
I found this in another post, I did it and I no longer have an error message ... Thanks

https://forum.arduino.cc/index.php?topic=647823.0 :  post of ToneArt  of 04/04/2020

If you want to avoid the warning, just fix the w5100.h file (in <Arduino install> \ libraries \ Ethernet \ src \ Utility):

at the end of the file you have :
#define htons(x) ( (((x)<<8)&0xFF00) | (((x)>>8)&0xFF) )

replace it with this
#define htons(x) ( ((((x)&0xFF)<<8)&0xFF00) | (((x)>>8)&0xFF) )

However, I only had this error message on my desktop computer and not on my other portable computer!

**Comment by evantill** [comment]
Still present using the latest version of the library (https://github.com/arduino-libraries/Ethernet/releases/tag/2.0.0)
