### ISSUE TITLE
ethernet.h + webserver.h

### ISSUE THREAD

**Issue by workpage2** [arduino-libraries/Ethernet#130]
Good afternoon.
Write example code ethernet.h and webserver.h
I have successfully used webserver.h with wifi (esp32), however this does not work with ethernet (w5500).
Thanks.
p.s. A similar question was here: https://github.com/espressif/arduino-esp32/issues/3580
But there is no answer (

**Comment by jandrassy** [comment]
the esp32 webserver is written for esp32 wifi library. it would even not work on esp8266.

you could try the new EthernetWebServer library by Khoi Hoang

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the [Arduino Forum](https://forum.arduino.cc). If you still need help, feel free to post over on the forum.
