### ISSUE TITLE
ESP32 HSPI

### ISSUE THREAD

**Issue by f3rn4ndes** [arduino-libraries/Ethernet#136]
Dear Sirs
how to setup the connection to HSPI (current use is to VSPI), at ESP32 framework ? 
Currently I am using  the VSPI to connect other hardware.

**Comment by peter1a** [comment]
Have you solved connecting ESP32 with HSPI? I'm also looking for some guides how to...

**Comment by per1234** [comment]
Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
