### ISSUE TITLE
Version 2.0.0 

### ISSUE THREAD

**Issue by rwlakin** [arduino-libraries/Ethernet#157]
After downloading Arduino 2.0.0beta4 cannot find ESP-12E board.  Loaded .ZIP and that didn't work either.  Worked OK with version 1.8.

**Comment by per1234** [comment]
HI @rwlakin. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests with the official Arduino Ethernet library. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please ask here:
https://forum.arduino.cc/index.php?board=150.0
