### ISSUE TITLE
How to reset w5500

### ISSUE THREAD

**Issue by SrRockabilly** [arduino-libraries/Ethernet#165]
Is there a way to reset by software? Is there a funtion like Ethernet.begin() that works in the other way around? In my aplication I cant use the reset pin. Thanks

**Comment by jandrassy** [comment]
> 
> 
> Is there a way to reset by software? Is there a funtion like Ethernet.begin() that works in the other way around? In my aplication I cant use the reset pin. Thanks

begin does a reset.
