### ISSUE TITLE
Support for LAN8720A possible

### ISSUE THREAD

**Issue by knopserl** [arduino-libraries/Ethernet#195]
would it be possible to support the LAN8720A network-Adapter used on several ESP32 boards (or seperate module).
There is an Ethernet Lib available which works but I can't use it as another library I need is the Artnet Library which requires this Arduino Standard Ethernet Library so I would like to use this one but it does only support Wiznet adapter.
Here is the lib/source which supports the LAN8720A
https://github.com/espressif/arduino-esp32/tree/master/libraries/Ethernet/src
And here is the ArtnetLib which is using the standard arduino-libraries/Ethernet lib and mostly the EthernetUDP class.
https://github.com/hideakitai/ArtNet

**Comment by JAndrassy** [comment]
no. W5x00 have TCP/IP stack in the firmware. LAN8720A requires TCP/P stack in the library
