### ISSUE TITLE
Trying to connect to Internet, show "Failed to configure Ethernet using DHCP"

### ISSUE THREAD

**Issue by HHavendano** [arduino-libraries/Ethernet#220]
hHi, i'm trying to connect my arduino to my office's internet. But it's showing "Failed to configure Ethernet using DHCP". I'm using the example "WebClient" ,and i change the "myDns" for the same serial as the Ethernet. the IP i change the last number for a number that nobody are using. Can someone know what's he problem? i think is the Industry's Internet.

**Comment by per1234** [comment]
Hi @HHavendano. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
