### ISSUE TITLE
Keep- Alive 

### ISSUE THREAD

**Issue by snnzdmr** [arduino-libraries/Ethernet#225]
how i set keep Alive timer ?  Sn_KPALVTR(0x002F) 
w5500/esp32

**Comment by per1234** [comment]
Hi @snnzdmr. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
