### ISSUE TITLE
Ability to connect 2 w5500 Modules and deal with them as objects

### ISSUE THREAD

**Issue by ohbhatt** [arduino-libraries/Ethernet#226]
I wish to create a rudimentary ethernet in/out - switch/hub where I can (sort of) daisy chain my boards. (I don't wish to use a ethernet switch/router/hub)
- One port would be acting as server
- The other would be acting as a client
(and forward any messages received on the first port after some processing/modification)

I am using an STM32 Bluepill with 2 Mini w5500 Modules (adafruit) connected via SPI. Nothing else is connected to SPI. All the other GPIOs are connected to relay drivers.
I have made sure they are connected to different CS pins and I have tried to assign Ethernet.init(); before doing anything with specific Ethernet modules but that keeps disconnecting and is working very unreliably.

I understand that some modification might be needed.

References:
https://forum.arduino.cc/t/2-network-shields/111509
https://forum.arduino.cc/t/connect-multiple-ethernet-shields-to-arduino-uno-using-spi/284008/16

But no one seems to have gotten it to work. Please help.

**Comment by per1234** [comment]
Hi @ohbhatt. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
