### ISSUE TITLE
<FlashStorage_STM32F1.h> problems with ethernet and Arduino OTA

### ISSUE THREAD

**Issue by zlomennypez** [arduino-libraries/Ethernet#228]
Hello, first thank you for all your work. I tried to send issue to FlashStorage_STM32F1.h, but it´s archived and unable to do that. If I use ethernet with stm32f103 and try to update firmware with https://github.com/JAndrassy/ArduinoOTA, it works until i use eeprom.put & eeprom.commit of your FlashStorage_STM32F1.h. after that OTA update doesn´t work and STM fw gets corrupted and stop working. Can you help me please? Thank you

**Comment by per1234** [comment]
Closing as off topic. @zlomennypez this issue tracker is only to be used to report bugs or feature requests specific to the Arduino Ethernet library.

You are welcome to request assistance on the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
