### ISSUE TITLE
ESP32 - W5500 communications error

### ISSUE THREAD

**Issue by philm001** [arduino-libraries/Ethernet#246]
Hello all, 

I have been having some trouble recently trying to get my ESP32 to communicate with the W5500 chip. 

I have my pinouts as follow:

SCK - 18
MISO - 19
MOSI - 23
SS - 0

What happens is that on these lines here:

```
writeMR(0x08);
	int someValue = readMR();
	Serial.println(String(someValue));
	if (someValue != 0x08) return 0;
	writeMR(0x10);
	someValue = readMR();
	Serial.println(String(someValue));
	if (someValue != 0x10) return 0;
	writeMR(0x00);
	if (readMR() != 0x00) return 0;
```

the variable someValue always returns 0. So it is as if the ESP32 is unable to communicate with the W5500. I tried the dev board that uses the W5100 and I am able to communicate with that chip. However, for some reason, I am unable to. Here is a snippet of my initilization code:

```
Serial.println("Enabling SPI");
    SPI.begin(SCLK_PIN, MISO_PIN, MOSI_PIN);
    Ethernet.init(SS_PIN);
    Ethernet.begin(mac, ip);

    Serial.println(Ethernet.hardwareStatus());
```

From what I can tell, I am not doing anything wrong. Please let me know

**Comment by per1234** [comment]
Hi @philm001. The "**esp32**" boards platform installation includes its own variant of the "Ethernet" library:

https://github.com/espressif/arduino-esp32/tree/master/libraries/Ethernet

That "platform bundled" library is used when you compile for an ESP32 board, not the standard "Ethernet" library that is hosted in this library.

So reports of problems using the "Ethernet" library with ESP32 boards are off topic for this issue tracker.
