### ISSUE TITLE
NFC module won't work after a Ethernet.begin(mac,ip)

### ISSUE THREAD

**Issue by agdl** [arduino-libraries/Ethernet#26]
_From @Sornii on April 4, 2014 17:46_

Hello,

I'm using im my project a NFC module created by elecfreaks, and it use a PN532 which can comunicate over SPI, I2C or UART.

Currenctly I had problems using this in I2C, and switched to SPI, it works when nothing but the module is used in Arduino, but when I initialize the Ethernet it won't work.

Is everything okay in the Ethernet library or is the library that I'm using to control the NFC module?

_Copied from original issue: arduino/Arduino#1987_

**Comment by PaulStoffregen** [comment]
Very likely this hardware problem: MISO tristate conflict *and* same CS pin.

http://www.carlh.net/blog/?p=45

Since this issue was from 2014 and lacks specific hardware details for a hardware problem, I'm going to close it.
