### ISSUE TITLE
[Ethernet] bunch of bugfix and improvements

### ISSUE THREAD

**Issue by agdl** [arduino-libraries/Ethernet#36]
_From @Fede85 on September 25, 2014 19:15_

Version 1.1 of the Ethernet library brings the following improvements:
* support for W5500 and W5200 Wiznet chipsets
* automatic detection of the Wiznet chipset
* SPI speed set to 14MHz, maximum allowed by the W5100 chipset
* generalized SPI_CS pin handling functions
* added getMaxSockets() method
* improved 3rd party compatibility using the SPI Extended API as a criterion of choice 
* removed redundant configurations and useless variable modifiers 

_Copied from original issue: arduino/Arduino/pull/2325_

**Comment by agdl** [comment]
_From @cmaglie on September 26, 2014 11:26_

@ArduinoBot  build this please

**Comment by agdl** [comment]
_From @ArduinoBot on September 26, 2014 23:56_

Build successful. Please test this code using one of the following:
http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-2325-BUILD-56-linux32.tgz
http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-2325-BUILD-56-linux64.tgz
http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-2325-BUILD-56-windows.zip
http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-2325-BUILD-56-macosx.zip

**Comment by agdl** [comment]
_From @cmaglie on October 1, 2014 17:20_

/cc @BAG28

I see, on another thread,  that you're searching for an Ethernet library with support for W5200, may you try this one? It should support W5100/5200/5500 with auto detection. I've tested it with a W5100 and W5500 but not with a W5200.

**Comment by agdl** [comment]
_From @embeddist on October 7, 2014 8:22_

@Fede85 

I will check/test "ide-1.5.x-ethernet-W5500-2" and feedback you until this week.

**Comment by agdl** [comment]
_From @BAG28 on October 25, 2014 16:18_

Hello, I dowloaded the whole SW today and checked the following with Example "Webserver"
Due + W5200 board 1  = assigned adress : most of times 0.0.0.0 sometimes erratic ones, in all cases  no ethernet answer
Due + W5200 board 2 = no serial print answer
Due + W5100 = KO (assigned adress stick to 255.255.255.255, even after many resets)

Uno + W5100 = OK
Uno + W5200 board 1 = assigned adress : most of times 0.0.0.0 sometimes erratic ones, in all cases  no ethernet answer
Uno + W5200 board 2 = assigned adress : always 0.0.0.0

Tries with Uno + W5200 board 2 and ethernet V2.0 found on internet is workin, so I think W5200 boards is working
For information
Uno  + W5200 board 2 with SD Cardinfo is working fine.
Due + W5200 board 2 with SD Cardinfo is working fine.

All tests done in same(~) conditions : ethernet cable, USB port and dvt environment : arduino-PR-2325-BUILD-56
I hope this will help. Thanks for having involved me, even if I can't help much more.

**Comment by agdl** [comment]
_From @BAG28 on November 10, 2014 7:12_

Hi,
I'm still doing some trials.
I changed the ethernet cable, after seeing poor refresh of my DHCP server.
After many trials, reets and so on I got
Due + W5100 board is working fine reapeatable. 
Same Sketch with Due + W5200 still not working
I observed that W5200 ship is heating-up on my two boards, and cannot touch it on board 1 after few seconds.
MAC adress is not seen on the network switch.
If I put some traces in W5200.cpp I can see that board is well detected.

**Comment by agdl** [comment]
_From @ffissore on November 12, 2014 9:24_

@ArduinoBot build this please

**Comment by agdl** [comment]
_From @ArduinoBot on November 12, 2014 11:45_

Build successful. Please test this code using one of the following:
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2325-BUILD-85-linux32.tgz
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2325-BUILD-85-linux64.tgz
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2325-BUILD-85-windows.zip
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2325-BUILD-85-macosx.zip

**Comment by agdl** [comment]
_From @cmaglie on November 13, 2014 14:35_

@BAG28 
thanks for the report! we got W5100 and W5500 working during our tests so, at least for them, we are now aligned with the results.

We didn't tried with a W5200 yet, after your test report we consider it not-working for now, unless someone else come up with a successful test.

**Comment by agdl** [comment]
_From @BAG28 on November 13, 2014 18:1_

Hi,
I am trying this version. 
It is better : MAC adress is recognized by my switch. Some packets are issued by W5200 on the network. When trying to connect to the board, some packets are received but no connexion.
When scanning the network with "FING" sw on android phone, IP adress and MAC adress are correctly seen, but scan services gives no services (should see port 80).

I will pursue testing, maybe with DHCP given IP adress. 
If you have some suggestions for testing, please let me know. If you need further information on my network layout, or other, please do not hesitate.

**Comment by agdl** [comment]
_From @BAG28 on November 13, 2014 18:28_

Hi again,
I did the test with DUE + Board 2, and I just tested on Uno + Board 1 : Same result.

**Comment by agdl** [comment]
_From @deonp on February 14, 2015 12:5_

I believe the problem with the W5200 is because CH_BASE is 0x0400 for W5100 and 0x4000 for W5200 but both currently have a fixed 0x0400.  I'll leave the implementation up to you @Fede85

**Comment by agdl** [comment]
_From @diverseg on April 13, 2015 21:51_

I agree with [deonp](https://github.com/deonp), I believe the problem with the W5200 not working is because CH_BASE is 0x0400 for W5100 and 0x4000 for W5200.
but the .h file has it fixed
  static const uint16_t CH_BASE = 0x0400;
 I have a W5200 and will change this to 0x4000 and try this tonight.
if it works I'll look at a better solution.

**Comment by agdl** [comment]
_From @PaulStoffregen on April 13, 2015 23:43_

Some time ago I created a modified Ethernet library that supports both W5100 & W5200 and automatically detects either.  The code is here, if anyone's interested.

https://github.com/PaulStoffregen/Ethernet

One small gotcha I ran into with the W5200 chip is the reset signal really is required.  I put it on pin 9.  I found the W5200 can get out of sync if it hears other SPI communication and never recovers, never properly realigns by only the CS signal.  If you don't use the reset signal, you can get lucky most of the time when other SPI chips aren't present.  But unlike the W5100, reset before initializing the W5200 seems to be the only 100% reliable way to make the W5200 work.

**Comment by agdl** [comment]
_From @deonp on April 14, 2015 3:52_

From memory there is also some issues with MAX_SOCK_NUM which is defined in Ethernet.h
The original MAX_SOCK_NUM was removed from the 5100.h file but there were two copies.
Therefore some changes are required to Ethernet / EthernetClient / EthernetUdp / EthernetServer objects as well to suit the 4 or 8 available sockets.

**Comment by agdl** [comment]
_From @cmaglie on May 12, 2015 14:57_

@ArduinoBot build this please

**Comment by agdl** [comment]
_From @cmaglie on May 12, 2015 14:58_

@diverseg @deonp @BAG28 
I've rebased the pull request and added the suggested fix for w5200.

**Comment by agdl** [comment]
_From @ArduinoBot on May 12, 2015 15:56_

Build successful. Please test this code using one of the following:
http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-2325-BUILD-269-linux32.tar.xz
http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-2325-BUILD-269-linux64.tar.xz
http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-2325-BUILD-269-windows.zip
http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-2325-BUILD-269-macosx.zip

**Comment by agdl** [comment]
_From @per1234 on June 12, 2015 10:21_

I have tested this library with Arduino IDE 1.6.5 Hourly Build 2015/06/12 10:42 using W5100 + Mega 2560, W5200 + UNO, and W5500 + Mega 2560. 

The ChatServer and UDPSendReceiveString examples with IP address specified work fine on all 3 Ethernet controller chips. I have not tested with DHCP. 

Let me know if there are any specific tests that would be helpful for me to do. I also have a Pro Micro I can use for testing.

Great work on this! I'd love to see it make it into 1.6.5.

**Comment by agdl** [comment]
_From @aslakr on November 2, 2015 15:24_

Since the ethernet library already is 1.1, but this isn't merged into that code, maybe this issue should be renamed accordingly?

**Comment by agdl** [comment]
_From @aslakr on November 2, 2015 15:28_

And maybe it should move to https://github.com/arduino-libraries/Ethernet ?

**Comment by agdl** [comment]
_From @cmaglie on November 3, 2015 9:56_

I've changed the name (and removed the reference to the version).
This one needs a rebase on the current master, we have it on our todo list.

**Comment by agdl** [comment]
_From @per1234 on November 3, 2015 10:34_

A significant number of the Ethernet related issues posted to the Arduino forum recently are related to people trying to use W5500 or W5200 with the Ethernet library. Quite often the solution they settle on is to switch to using the .org IDE despite me explaining other options.

I've been using a slightly modified version of this library for 4.5 months continuously without finding any issues. I have had no reports of issues on my fork of it and I know there are at least a few other users.

**Comment by q2dg** [comment]
I think this issue should be opened as still it is not resolved.

Why the related PR (https://github.com/arduino/Arduino/pull/2325) hasn't more love? It can solve https://github.com/arduino-libraries/Ethernet/issues/37 and https://github.com/arduino-libraries/Ethernet/issues/38 issues, at least!!

In fact, these issue are already solved in a fork that could deserve some attention: https://github.com/per1234/EthernetMod. In addition to former issues and PRs, It solves many other problems. For instance, it alse merges what it was left out  in https://github.com/arduino/Arduino/pull/1700, (and, sadly, forgotten many time ago). This comment it very worthy: https://github.com/per1234/EthernetMod/issues/3#issuecomment-238075126
