### ISSUE TITLE
Give the option to specify another SS pin instead of the static nº10

### ISSUE THREAD

**Issue by q2dg** [arduino-libraries/Ethernet#38]
The reason: now there's no official Ethernet Shield, so for doing this library more compatible/generic with the wild, I think this functionality could be another nice step to it (in addition to https://github.com/arduino-libraries/Ethernet/issues/37).

A suggestion of implementation is here: http://forum.arduino.cc/index.php?topic=217423.msg1601862#msg1601862

Thanks

**Comment by agdl** [comment]
@sandeepmistry maybe we can add this https://github.com/arduino-libraries/WiFi101/pull/58 :)

**Comment by PaulStoffregen** [comment]
Version 2.0.0 will have Ethernet.init(cspin)

**Comment by PaulStoffregen** [comment]
Fixed
