### ISSUE TITLE
Parsing example sketch

### ISSUE THREAD

**Issue by martinius96** [arduino-libraries/Ethernet#52]
Hello there I am looking for sketch for parsing string to variable from .txt file. For instance i want to download if led is on/off when i am controlling it throught webserver. I have this solution on NodeMCU, which i use only for HTTPS requests. But for HTTP i want to use Ethernet shield. So can you please send me sketch? Thanks a  lot!

**Comment by martinius96** [comment]
Some .ino?

**Comment by PaulStoffregen** [comment]
Github is the wrong place to ask.

Ask for help here:
https://forum.arduino.cc/
