### ISSUE TITLE
Grammar corrections in ethernet reference

### ISSUE THREAD

**Issue by sterretje** [arduino-libraries/Ethernet#53]
And now hopefully in the correct section

https://www.arduino.cc/en/Reference/Ethernet

I picked up the following. Note that I'm not native English speaking, so might have some things wrong.

>The libraries are allow an Arduino board to connect to the internet.

'are' to be removed

> The libraries support up to four concurrent connection (incoming or outgoing or a combination).

'connection' to be changed to 'connections'

**Comment by per1234** [comment]
Fixed during the 2.0 release documentation updates: https://github.com/arduino-libraries/Ethernet/issues/67
