### ISSUE TITLE
why doesn't this library support the Ethernet Shield you're selling?

### ISSUE THREAD

**Issue by greyltc** [arduino-libraries/Ethernet#55]
This library does not support the [official shield](https://store.arduino.cc/usa/arduino-ethernet-rev3-without-poe) I just bought. Is that surprising to anyone else?

**Comment by per1234** [comment]
See https://github.com/arduino-libraries/Ethernet/issues/37

**Comment by greyltc** [comment]
Is there any other example of an official Arduino product that doesn't have official library support?

**Comment by PaulStoffregen** [comment]
Closing this, since it's a duplicate.  Working now on code to become version 2.0.0.  If you're interested, please give it a try and let me know if you find any issues or have any other concerns.

https://github.com/PaulStoffregen/Ethernet
