### ISSUE TITLE
Library 2.0 Bug with Arduino Micro

### ISSUE THREAD

**Issue by bitShakeMX** [arduino-libraries/Ethernet#93]
Arduino:1.8.8 (Windows 10), Tarjeta:"Arduino/Genuino Micro"

In function 'global constructors keyed to 65535_0_WebClient.ino.cpp.o':

lto1.exe: internal compiler error: Segmentation fault

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Users\PonchO\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\5.4.0-atmel3.6.1-arduino2/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/users/poncho/appdata/local/arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

Se encontraron varias bibliotecas para "Ethernet.h"
Usado: C:\Users\PonchO\Documents\Arduino\libraries\Ethernet
 No usado: C:\Program Files (x86)\Arduino\libraries\Ethernet
exit status 1
Error compilando para la tarjeta Arduino/Genuino Micro.
Librería inválida encontrada en C:\Users\PonchO\Documents\Arduino\libraries\OV7670FIFO: No encontrado archivos de encabezado (.h) en C:\Users\PonchO\Documents\Arduino\libraries\OV7670FIFO

Este informe podría contener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/7949
